version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: phone_repair_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: phone_repair_db
      MYSQL_USER: phone_repair_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - phone_repair_network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phone_repair_phpmyadmin
    restart: always
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: rootpassword123
    ports:
      - "8080:80"
    networks:
      - phone_repair_network

volumes:
  mysql_data:

networks:
  phone_repair_network:
    driver: bridge